### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by dmaynor** [IOActive/Platbox#5]
Is this suppose to work on Linux. My attempts to get it running are met with 
"install_driver Unimplemented!" and
"start_service Unimplemented!"

I cloned the repo and did ./build.sh in the main directory. I cded to Platbox/compiled
and tried to get both the paltboc_cli and the example to work but were meant with the unimplemented errors.

I wanted to make sure I wasn't doing something wrong before looking at writing the linux support.

**Comment by n3k** [comment]
There is Linux support indeed. You need to compile the driver and load it manually however. If you copy the compiled driver into the same directory where platbox_cli is, you can then use "platbox_cli start".
