### ISSUE TITLE
Arehe tests useful for fwupd Host Firmware Security checks?

### ISSUE THREAD

**Issue by hughsie** [IOActive/Platbox#6]
Hi all,

I wondered if any of these tests would be appropriate for HSI? e.g. https://fwupd.github.io/libfwupdplugin/hsi.html -- any feedback most welcome. Thanks!

**Comment by n3k** [comment]
We're covering a lot of the same concept. We are not following the names suggested by that specification though.

**Comment by hughsie** [comment]
> We're covering a lot of the same concept

Ohh my reason for opening the bug was more of an initial opener on whether you'd like to work together more in the future. It seems there's a lot of overlap, and it might be beneficial to "cross pollinate" if you see what I mean. I do talk to both Intel and AMD fairly regularly, and the latter at least seems a lot more receptive to adding bits to the kernel to expose security attributes to userspace.
