### ISSUE TITLE
Cannot find source file:   Acer/SpiAccessViaSmi.cpp

### ISSUE THREAD

**Issue by littlewhitex** [IOActive/Platbox#7]
Hi，I am compiling on windows and I am getting the following error, file Acer/SpiAccessViaSmi.cpp not found!
Is it just me not doing it right? Hope you can give some pointers, thanks.

D:\Tmp\platbox\Platbox-main\Platbox-main\build>cmake --build build64/ --config Release
CMake is re-running because D:/Tmp/platbox/Platbox-main/Platbox-main/build/build64/CMakeFiles/generate.stamp dependency file is missing.
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- Configuring done
CMake Error at pocs/CMakeLists.txt:36 (add_executable):
  Cannot find source file:

    Acer/SpiAccessViaSmi.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at pocs/CMakeLists.txt:36 (add_executable):
  No SOURCES given to target: AcerSpiAccessViaSmiPoc

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by n3k** [comment]
Yes, we forgot that entry in the cmakelist. We have updated it just now. Thanks
